name: Latest blog post workflow
on:
  push:
  schedule: # Run workflow automatically
    - cron: '0 10 * * 1' # Runs every monday, at 10 a.m
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: BLOG-POST-LIST
          max_post_count: 8
          feed_list: 'https://dev.to/feed/douglasamarelo'
